AffinityWorkforceAppBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AffinityWorkforceAppBundle:Default:index }

AffinityWorkforceAppBundle_dashboard:
    pattern: /dashboard
    defaults: { _controller: AffinityWorkforceAppBundle:Dashboard:index }
    
AffinityWorkforce_dashboard_manager:
    pattern: /dashboard/manager
    defaults: { _controller: AffinityWorkforceAppBundle:Dashboard:managerDashboard }