parameters:
    affinity.workforce.account_service.class: Affinity\Workforce\AppBundle\Services\AccountService

services:
    affinity.workforce.account_service:
        class: %affinity.workforce.account_service.class%
