login:
  pattern:  /account/login
  defaults: { _controller: AffinityWorkforceAppBundle:Account:login }
  
login_check:
  pattern:  /account/login_check
  
logout:
  pattern:  /account/logout

AffinityWorkforceAppBundle:
    resource: "@AffinityWorkforceAppBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
