security:
    
    firewalls:
        main:
            pattern: ^/
            anonymous: ~
    
    access_control:
      
    providers:
        in_memory:
      
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
      