security:
    
    firewalls:
        login:
            pattern:  ^/account/login$
            anonymous: ~
        
        register:
            pattern:  ^/account/register
            anonymous: ~
            
        application:
            pattern: ^/
            logout:
                path: /account/logout
                target: /account/login
            form_login:
                login_path:  /account/login
                check_path:  /account/login_check
    
    access_control:
      
    providers:
        main:
            entity: { class: Affinity\Workforce\AppBundle\Entity\Employee, property: username }
      
    encoders:
        Affinity\Workforce\AppBundle\Entity\Employee: sha512
            
      